spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deal?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: MM-dd-yyyy HH:mm:ss

